#+title: A Deep-Learning Approach to Breast Cancer Screening from Mammography Images
#+setupfile: setupfile.org
#+OPTIONS: toc:t
#+AUTHOR: Laurent Lejeune
#+EMAIL: me@lejeunel.org
#+cite_export: biblatex
#+bibliography: myrefs.bib
#+LATEX_HEADER: \bibliography{myrefs.bib}

#+BEGIN_SRC python :exports none :session
from pathlib import Path
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import random
import torch
matplotlib.use("tkagg")

from obj_detection.dataloader import CarDataset
#+END_SRC
#+RESULTS:
: None

* Mammography Dataset

We use the publicly available Chinese Mammography Database (CMMD) [cite:@cai23],
which originally contains $\approx 1871$ patients screened for breast cancer.
and filter-out  scans that match the following criteria:

- Patients with history of previous breast biopsy within 1 week, or any therapy for breast lesions
  prior to mammography
- Patients with breasts prosthesis
- Images with substantial motion artifact

This reduces our dataset to $1775$ patients.
Each case is then analyzed by domain experts so as to assign to each *image* the following
target variables:
- $y_{p} \in \{\text{benign}, \text{malignant}\, \text{none}\}$ indicates the type of tumor, or ~none~ when sample is sane.
- $y_{a} \in \{\text{calcification}, \text{mass}, \text{both}\}$ indicates the type of abnormality, where ~both~ means that both ~calcification~ and ~mass~ are present.
- $y_s \in \{\text{luminal-A}, \text{luminal-B},\text{HER2-positive},\text{triple-negative},\text{missing}\}$ a
  subtype information (possibly missing).


* Dataset exploration

#+print_bibliography:
