#+title: A Deep-Learning Approach to Breast Cancer Screening from Mammography Images
#+setupfile: setupfile.org
#+OPTIONS: toc:t
#+AUTHOR: Laurent Lejeune
#+EMAIL: me@lejeunel.org
#+cite_export: biblatex
#+bibliography: myrefs.bib
#+LATEX_HEADER: \bibliography{myrefs.bib}

#+BEGIN_SRC python :exports none :session
from pathlib import Path
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import random
import torch
matplotlib.use("tkagg")

from obj_detection.dataloader import CarDataset
#+END_SRC
#+RESULTS:
: None

* Mammography Dataset

We use the publicly available Chinese Mammography Database (CMMD) [cite:@cai23],
which originally contains $\approx 1871$ patients screened for breast cancer.
and apply the following filtering criteria to obtain $1775$ scans:

- Patients with history of previous breast biopsy within 1 week, or any therapy for breast lesions
  prior to mammography
- Patients with breasts prosthesis
- Images with substantial motion artifact

Each patient is then diagnosed by an expert and assigned the following target variables:
- $y_{p} \in \{\text{benign}, \text{malignant}\}$ indicates the type of tumor.
- $y_{a} \in \{\text{calcification}, \text{mass}, \text{both}\}$ indicates the type of abnormality, where ~both~ means that both ~calcification~ and ~mass~ are present.
- $y_s \in \{\text{luminal-A}, \text{luminal-B},\text{HER2-positive},\text{triple-negative},\text{missing}\}$ a
  subtype information (possibly missing).


* Dataset exploration

#+print_bibliography:
