[tool.poetry]
name = "hera-mi-test"
version = "0.1.0"
description = "Research Engineer Entrance Test"
authors = ["Laurent Lejeune <me@lejeunel.org>"]
readme = "README.org"
packages = [{include = 'hmtest'}]

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
